spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    platform: mysql
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net:3306
    database:
    username: be951e7d1607c2
    password: 9c1d1edd
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 8
  mail:
    host: smtp.gmail.com
    port: 587
    username: petassistantpracainz@gmail.com
    password: pracainz2k18
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
jwt:
  token:
    secret: secret
    algorithm: HS512
    expiration: 10000
server:
  port: ${PORT:5000}