spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  datasource:
    platform: postgresql
    url: jdbc:postgresql://ec2-54-83-8-246.compute-1.amazonaws.com:5432/ddrg3d2k863tne
    username: vwzilrfplhbycv
    password: 9abd922d2a350a6c4fc5e5728e2d7ec59020ccd93c6dcb14a6da216697259cae
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: petassistantpracainz@gmail.com
    password: pracainz2k18
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
jwt:
  token:
    secret: secret
    algorithm: HS512
    expiration: 10000
server:
  port: ${PORT:5000}