spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/pet_assistant
    username: petassistant
    password: petassistant
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: petassistantpracainz@gmail.com
    password: pracainz2k18
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true