spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/pet_assistant?serverTimezone=UTC
    username: petassistant
    password: petassistant
    driverClassName: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: petassistantpracainz@gmail.com
    password: pracainz2k18
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            trust: smtp.gmail.com
jwt:
  token:
    secret: secret
    algorithm: HS512
    expiration: 10000
server:
  port: 8081